-- Seed Data for Cloudflare D1
-- Generated from curated starter exams

INSERT OR IGNORE INTO exams (id, user_id, author_display_name, title, subject, description, difficulty, question_count, is_public, tags, created_at, updated_at) VALUES ('seed_cb949ffc', 'seed_author', 'CodeMaster #482a', 'Computer Science: Algorithms & Data Structures', 'Computer Science', 'Fundamental algorithmic analysis, sorting complexities, binary heaps, and graph traversals.', 'medium', 5, 1, '["Algorithms","DataStructures","BigO"]', unixepoch(), unixepoch());
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_c39ca938', 'seed_cb949ffc', 1, 'multiple-choice', 'What is the worst-case time complexity of QuickSort when using a naive pivot selection on an already sorted array?', '["O(n log n)","O(n)","O(n²)","O(log n)"]', 'O(n²)', 'When a naive pivot is selected on already sorted data, partitioning results in subproblems of sizes 0 and n-1, leading to quadratic O(n²) comparisons.');
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_5da102f3', 'seed_cb949ffc', 2, 'multiple-choice', 'Which data structure is fundamentally utilized to implement Breadth-First Search (BFS) in a graph?', '["Stack","Queue","Min-Heap","Disjoint Set"]', 'Queue', 'BFS explores neighbors level-by-level using a FIFO (First-In, First-Out) Queue to order vertices by distance from the source.');
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_e1b3323e', 'seed_cb949ffc', 3, 'true-false', 'An AVL tree guarantees that the height difference between left and right subtrees for any node never exceeds 1.', '["True","False"]', 'True', 'The AVL balancing criterion strictly enforces that the balance factor (height(left) - height(right)) for every node is in {-1, 0, 1}.');
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_cbbd5aa8', 'seed_cb949ffc', 4, 'multiple-choice', 'What is the space complexity of Depth-First Search (DFS) on a balanced binary tree with N nodes?', '["O(N)","O(log N)","O(1)","O(N²)"]', 'O(log N)', 'For a balanced binary tree, the maximum call stack depth corresponds to the tree height h = O(log N).');
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_1e18089e', 'seed_cb949ffc', 5, 'short-answer', 'Name the algorithmic paradigm used by Dijkstra algorithm to find the shortest path in a weighted graph with non-negative edges.', NULL, 'Greedy', 'Dijkstra algorithm is a greedy algorithm that repeatedly selects the vertex with the minimal tentative distance from the unvisited set.');

INSERT OR IGNORE INTO exams (id, user_id, author_display_name, title, subject, description, difficulty, question_count, is_public, tags, created_at, updated_at) VALUES ('seed_15c2220f', 'seed_author', 'MathWhiz #9c1f', 'Mathematics: Differential Calculus & Limits', 'Mathematics', 'Derivative rules, L Hôpital limit evaluations, continuity, and critical value optimization.', 'hard', 3, 1, '["Calculus","Limits","Derivatives"]', unixepoch(), unixepoch());
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_1ba5fddc', 'seed_15c2220f', 1, 'multiple-choice', 'What is the derivative of f(x) = ln(3x² + 1) with respect to x?', '["6x / (3x² + 1)","1 / (3x² + 1)","6x ln(3x² + 1)","3x / (3x² + 1)"]', '6x / (3x² + 1)', 'By the chain rule, d/dx[ln(u)] = (1/u) * u''. Here u = 3x² + 1 and u'' = 6x, so the derivative is 6x / (3x² + 1).');
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_d6573311', 'seed_15c2220f', 2, 'multiple-choice', 'Evaluate the limit: lim (x -> 0) [sin(5x) / x].', '["0","1","5","Does not exist"]', '5', 'Using the fundamental trigonometric limit lim (u -> 0) [sin(u)/u] = 1, rewrite as 5 * lim (x -> 0) [sin(5x) / (5x)] = 5 * 1 = 5.');
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_841bb452', 'seed_15c2220f', 3, 'true-false', 'If a function f(x) is continuous at x = c, then f(x) is guaranteed to be differentiable at x = c.', '["True","False"]', 'False', 'Continuity does not imply differentiability. The classic counterexample is f(x) = |x| at x = 0, which is continuous but has a sharp corner (no unique tangent line).');

INSERT OR IGNORE INTO exams (id, user_id, author_display_name, title, subject, description, difficulty, question_count, is_public, tags, created_at, updated_at) VALUES ('seed_58c56998', 'seed_author', 'BioPro #3d88', 'Biology: Cellular Respiration & ATP Synthesis', 'Biology', 'Glycolysis, the Krebs cycle, oxidative phosphorylation, and mitochondrial ATP synthase.', 'easy', 3, 1, '["CellBiology","Respiration","Mitochondria"]', unixepoch(), unixepoch());
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_eb64f6df', 'seed_58c56998', 1, 'multiple-choice', 'In eukaryotic cells, where does glycolysis take place?', '["Mitochondrial matrix","Cytoplasm","Inner mitochondrial membrane","Nucleus"]', 'Cytoplasm', 'Glycolysis is the universal initial pathway of glucose breakdown and takes place entirely in the cytosol / cytoplasm.');
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_38e1f1ef', 'seed_58c56998', 2, 'multiple-choice', 'Which organelle is widely referred to as the powerhouse of the cell due to producing the majority of cellular ATP?', '["Endoplasmic Reticulum","Golgi Apparatus","Mitochondria","Lysosome"]', 'Mitochondria', 'Mitochondria perform the citric acid cycle and oxidative phosphorylation, generating the bulk of the cell ATP.');
INSERT OR IGNORE INTO questions (id, exam_id, "order", type, question, options, correct_answer, explanation) VALUES ('seed_q_59a13ae9', 'seed_58c56998', 3, 'true-false', 'Anaerobic fermentation yields significantly more ATP molecules per glucose molecule than aerobic cellular respiration.', '["True","False"]', 'False', 'Fermentation produces only 2 net ATP per glucose (from glycolysis), whereas aerobic cellular respiration produces approximately 30-32 ATP.');

