/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as MyExamsRouteImport } from './routes/my-exams'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsAndPrivacyRouteImport } from './routes/terms-and-privacy'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'
import { Route as PracticeAttemptIdRouteImport } from './routes/practice.$attemptId'
import { Route as ResultsAttemptIdRouteImport } from './routes/results.$attemptId'
import { Route as ApiAttemptsIndexRouteImport } from './routes/api/attempts/index'
import { Route as ApiAttemptsIdRouteImport } from './routes/api/attempts/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDocumentsInitiateRouteImport } from './routes/api/documents/initiate'
import { Route as ApiExamExplainRouteImport } from './routes/api/exam/explain'
import { Route as ApiExamGenerateRouteImport } from './routes/api/exam/generate'
import { Route as ApiExamsIndexRouteImport } from './routes/api/exams/index'
import { Route as ApiExamsIdRouteImport } from './routes/api/exams/$id'
import { Route as ApiUserDeleteRouteImport } from './routes/api/user/delete'
import { Route as ApiUserMeRouteImport } from './routes/api/user/me'
import { Route as ApiDocumentsIdStatusRouteImport } from './routes/api/documents/$id/status'
import { Route as ApiDocumentsIdUploadRouteImport } from './routes/api/documents/$id/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const MyExamsRoute = MyExamsRouteImport.update({
  id: '/my-exams',
  path: '/my-exams',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndPrivacyRoute = TermsAndPrivacyRouteImport.update({
  id: '/terms-and-privacy',
  path: '/terms-and-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeAttemptIdRoute = PracticeAttemptIdRouteImport.update({
  id: '/practice/$attemptId',
  path: '/practice/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttemptsIndexRoute = ApiAttemptsIndexRouteImport.update({
  id: '/api/attempts/',
  path: '/api/attempts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttemptsIdRoute = ApiAttemptsIdRouteImport.update({
  id: '/api/attempts/$id',
  path: '/api/attempts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsInitiateRoute = ApiDocumentsInitiateRouteImport.update({
  id: '/api/documents/initiate',
  path: '/api/documents/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamExplainRoute = ApiExamExplainRouteImport.update({
  id: '/api/exam/explain',
  path: '/api/exam/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamGenerateRoute = ApiExamGenerateRouteImport.update({
  id: '/api/exam/generate',
  path: '/api/exam/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamsIndexRoute = ApiExamsIndexRouteImport.update({
  id: '/api/exams/',
  path: '/api/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamsIdRoute = ApiExamsIdRouteImport.update({
  id: '/api/exams/$id',
  path: '/api/exams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserDeleteRoute = ApiUserDeleteRouteImport.update({
  id: '/api/user/delete',
  path: '/api/user/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserMeRoute = ApiUserMeRouteImport.update({
  id: '/api/user/me',
  path: '/api/user/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsIdStatusRoute = ApiDocumentsIdStatusRouteImport.update({
  id: '/api/documents/$id/status',
  path: '/api/documents/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentsIdUploadRoute = ApiDocumentsIdUploadRouteImport.update({
  id: '/api/documents/$id/upload',
  path: '/api/documents/$id/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/discover': typeof DiscoverRoute
  '/generate': typeof GenerateRoute
  '/my-exams': typeof MyExamsRoute
  '/settings': typeof SettingsRoute
  '/terms-and-privacy': typeof TermsAndPrivacyRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/practice/$attemptId': typeof PracticeAttemptIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/api/attempts/$id': typeof ApiAttemptsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/initiate': typeof ApiDocumentsInitiateRoute
  '/api/exam/explain': typeof ApiExamExplainRoute
  '/api/exam/generate': typeof ApiExamGenerateRoute
  '/api/exams/$id': typeof ApiExamsIdRoute
  '/api/user/delete': typeof ApiUserDeleteRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/api/attempts/': typeof ApiAttemptsIndexRoute
  '/api/exams/': typeof ApiExamsIndexRoute
  '/api/documents/$id/status': typeof ApiDocumentsIdStatusRoute
  '/api/documents/$id/upload': typeof ApiDocumentsIdUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/discover': typeof DiscoverRoute
  '/generate': typeof GenerateRoute
  '/my-exams': typeof MyExamsRoute
  '/settings': typeof SettingsRoute
  '/terms-and-privacy': typeof TermsAndPrivacyRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/practice/$attemptId': typeof PracticeAttemptIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/api/attempts/$id': typeof ApiAttemptsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/initiate': typeof ApiDocumentsInitiateRoute
  '/api/exam/explain': typeof ApiExamExplainRoute
  '/api/exam/generate': typeof ApiExamGenerateRoute
  '/api/exams/$id': typeof ApiExamsIdRoute
  '/api/user/delete': typeof ApiUserDeleteRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/api/attempts': typeof ApiAttemptsIndexRoute
  '/api/exams': typeof ApiExamsIndexRoute
  '/api/documents/$id/status': typeof ApiDocumentsIdStatusRoute
  '/api/documents/$id/upload': typeof ApiDocumentsIdUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/discover': typeof DiscoverRoute
  '/generate': typeof GenerateRoute
  '/my-exams': typeof MyExamsRoute
  '/settings': typeof SettingsRoute
  '/terms-and-privacy': typeof TermsAndPrivacyRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/practice/$attemptId': typeof PracticeAttemptIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/api/attempts/$id': typeof ApiAttemptsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/documents/initiate': typeof ApiDocumentsInitiateRoute
  '/api/exam/explain': typeof ApiExamExplainRoute
  '/api/exam/generate': typeof ApiExamGenerateRoute
  '/api/exams/$id': typeof ApiExamsIdRoute
  '/api/user/delete': typeof ApiUserDeleteRoute
  '/api/user/me': typeof ApiUserMeRoute
  '/api/attempts/': typeof ApiAttemptsIndexRoute
  '/api/exams/': typeof ApiExamsIndexRoute
  '/api/documents/$id/status': typeof ApiDocumentsIdStatusRoute
  '/api/documents/$id/upload': typeof ApiDocumentsIdUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/discover'
    | '/generate'
    | '/my-exams'
    | '/settings'
    | '/terms-and-privacy'
    | '/exam/$examId'
    | '/practice/$attemptId'
    | '/results/$attemptId'
    | '/api/attempts/$id'
    | '/api/auth/$'
    | '/api/documents/initiate'
    | '/api/exam/explain'
    | '/api/exam/generate'
    | '/api/exams/$id'
    | '/api/user/delete'
    | '/api/user/me'
    | '/api/attempts/'
    | '/api/exams/'
    | '/api/documents/$id/status'
    | '/api/documents/$id/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/discover'
    | '/generate'
    | '/my-exams'
    | '/settings'
    | '/terms-and-privacy'
    | '/exam/$examId'
    | '/practice/$attemptId'
    | '/results/$attemptId'
    | '/api/attempts/$id'
    | '/api/auth/$'
    | '/api/documents/initiate'
    | '/api/exam/explain'
    | '/api/exam/generate'
    | '/api/exams/$id'
    | '/api/user/delete'
    | '/api/user/me'
    | '/api/attempts'
    | '/api/exams'
    | '/api/documents/$id/status'
    | '/api/documents/$id/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/discover'
    | '/generate'
    | '/my-exams'
    | '/settings'
    | '/terms-and-privacy'
    | '/exam/$examId'
    | '/practice/$attemptId'
    | '/results/$attemptId'
    | '/api/attempts/$id'
    | '/api/auth/$'
    | '/api/documents/initiate'
    | '/api/exam/explain'
    | '/api/exam/generate'
    | '/api/exams/$id'
    | '/api/user/delete'
    | '/api/user/me'
    | '/api/attempts/'
    | '/api/exams/'
    | '/api/documents/$id/status'
    | '/api/documents/$id/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  DiscoverRoute: typeof DiscoverRoute
  GenerateRoute: typeof GenerateRoute
  MyExamsRoute: typeof MyExamsRoute
  SettingsRoute: typeof SettingsRoute
  TermsAndPrivacyRoute: typeof TermsAndPrivacyRoute
  ExamExamIdRoute: typeof ExamExamIdRoute
  PracticeAttemptIdRoute: typeof PracticeAttemptIdRoute
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRoute
  ApiAttemptsIdRoute: typeof ApiAttemptsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDocumentsInitiateRoute: typeof ApiDocumentsInitiateRoute
  ApiExamExplainRoute: typeof ApiExamExplainRoute
  ApiExamGenerateRoute: typeof ApiExamGenerateRoute
  ApiExamsIdRoute: typeof ApiExamsIdRoute
  ApiUserDeleteRoute: typeof ApiUserDeleteRoute
  ApiUserMeRoute: typeof ApiUserMeRoute
  ApiAttemptsIndexRoute: typeof ApiAttemptsIndexRoute
  ApiExamsIndexRoute: typeof ApiExamsIndexRoute
  ApiDocumentsIdStatusRoute: typeof ApiDocumentsIdStatusRoute
  ApiDocumentsIdUploadRoute: typeof ApiDocumentsIdUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-exams': {
      id: '/my-exams'
      path: '/my-exams'
      fullPath: '/my-exams'
      preLoaderRoute: typeof MyExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-privacy': {
      id: '/terms-and-privacy'
      path: '/terms-and-privacy'
      fullPath: '/terms-and-privacy'
      preLoaderRoute: typeof TermsAndPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$attemptId': {
      id: '/practice/$attemptId'
      path: '/practice/$attemptId'
      fullPath: '/practice/$attemptId'
      preLoaderRoute: typeof PracticeAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$attemptId': {
      id: '/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof ResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attempts/': {
      id: '/api/attempts/'
      path: '/api/attempts'
      fullPath: '/api/attempts/'
      preLoaderRoute: typeof ApiAttemptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attempts/$id': {
      id: '/api/attempts/$id'
      path: '/api/attempts/$id'
      fullPath: '/api/attempts/$id'
      preLoaderRoute: typeof ApiAttemptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/initiate': {
      id: '/api/documents/initiate'
      path: '/api/documents/initiate'
      fullPath: '/api/documents/initiate'
      preLoaderRoute: typeof ApiDocumentsInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exam/explain': {
      id: '/api/exam/explain'
      path: '/api/exam/explain'
      fullPath: '/api/exam/explain'
      preLoaderRoute: typeof ApiExamExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exam/generate': {
      id: '/api/exam/generate'
      path: '/api/exam/generate'
      fullPath: '/api/exam/generate'
      preLoaderRoute: typeof ApiExamGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exams/': {
      id: '/api/exams/'
      path: '/api/exams'
      fullPath: '/api/exams/'
      preLoaderRoute: typeof ApiExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exams/$id': {
      id: '/api/exams/$id'
      path: '/api/exams/$id'
      fullPath: '/api/exams/$id'
      preLoaderRoute: typeof ApiExamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/delete': {
      id: '/api/user/delete'
      path: '/api/user/delete'
      fullPath: '/api/user/delete'
      preLoaderRoute: typeof ApiUserDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/me': {
      id: '/api/user/me'
      path: '/api/user/me'
      fullPath: '/api/user/me'
      preLoaderRoute: typeof ApiUserMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$id/status': {
      id: '/api/documents/$id/status'
      path: '/api/documents/$id/status'
      fullPath: '/api/documents/$id/status'
      preLoaderRoute: typeof ApiDocumentsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/documents/$id/upload': {
      id: '/api/documents/$id/upload'
      path: '/api/documents/$id/upload'
      fullPath: '/api/documents/$id/upload'
      preLoaderRoute: typeof ApiDocumentsIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  DiscoverRoute: DiscoverRoute,
  GenerateRoute: GenerateRoute,
  MyExamsRoute: MyExamsRoute,
  SettingsRoute: SettingsRoute,
  TermsAndPrivacyRoute: TermsAndPrivacyRoute,
  ExamExamIdRoute: ExamExamIdRoute,
  PracticeAttemptIdRoute: PracticeAttemptIdRoute,
  ResultsAttemptIdRoute: ResultsAttemptIdRoute,
  ApiAttemptsIdRoute: ApiAttemptsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDocumentsInitiateRoute: ApiDocumentsInitiateRoute,
  ApiExamExplainRoute: ApiExamExplainRoute,
  ApiExamGenerateRoute: ApiExamGenerateRoute,
  ApiExamsIdRoute: ApiExamsIdRoute,
  ApiUserDeleteRoute: ApiUserDeleteRoute,
  ApiUserMeRoute: ApiUserMeRoute,
  ApiAttemptsIndexRoute: ApiAttemptsIndexRoute,
  ApiExamsIndexRoute: ApiExamsIndexRoute,
  ApiDocumentsIdStatusRoute: ApiDocumentsIdStatusRoute,
  ApiDocumentsIdUploadRoute: ApiDocumentsIdUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
